# Generated by Django 4.1.4 on 2022-12-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_lot_hammer_amount_lot_hammer_url_lot_letter_lot_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='has_lot_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
