# Generated by Django 4.1.4 on 2022-12-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lots.lot'),
            preserve_default=False,
        ),
    ]
