# Generated by Django 4.1.4 on 2022-12-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_item_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='technique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
