# Generated by Django 4.1.4 on 2023-01-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_alter_art_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='auction_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='auction_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='decade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='end_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='has_info_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='start_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
